package com.vinegrad.estateagents;

import static com.vinegrad.estateagents.model.ListingType.FOR_SALE;
import static com.vinegrad.estateagents.model.ListingType.TO_LET;
import static com.vinegrad.estateagents.model.PropertyType.BUNGALOW;
import static com.vinegrad.estateagents.model.PropertyType.DETACHED;
import static com.vinegrad.estateagents.model.PropertyType.FLAT;
import static com.vinegrad.estateagents.model.PropertyType.SEMI_DETACHED;
import static com.vinegrad.estateagents.model.PropertyType.TERRACED;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import com.vinegrad.estateagents.model.Property;
import com.vinegrad.estateagents.service.PropertyService;

@SpringBootApplication
public class EstateAgentsApplication implements CommandLineRunner {

	@Autowired
	private PropertyService service;
	
	public static void main(String[] args) {
		SpringApplication.run(EstateAgentsApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
		service.deleteAllProperties();
		for(int i = 0; i < 100000; i++) {
		service.saveAllProperties(List.of(new Property(FOR_SALE, 150000, DETACHED, "Hull", 3, "This detached home is located on Kingswood, close to well regarded schools and local amenities including a supermarket, a cinema and a range of retail outlets and restaurants. The property would be perfect for a family as it is ready to move into and offers ample living space. The property is available with no onward chain and benefits from front and rear gardens as well as a garage with off-street parking space and internally boasts a gorgeous living room, a stunning kitchen/diner with utility room off, a convenient downstairs WC, two double bedrooms with en-suite shower-room to master, a single third bedroom and a stylish family bathroom.", "https://media.rightmove.co.uk/dir/crop/10:9-16:9/150k/149891/90446150/149891_66cad1ff-17c7-4044-ad90-d4320d5e813a-283_4_37_101368_IMG_01_0000_max_476x317.jpg"),
				new Property(FOR_SALE, 120000, SEMI_DETACHED, "Hull", 4, "This stunning bay fronted semi detached house stands in the highly desirable and leafy street scene of Elms Drive, ideally placed for local schools, shops and amenities. With its wealth of character and modern fittings this super family home also has the benefit of a good sized garden to enjoy. The accommodation has gas fired central heating, double glazing and comprises a spacious hallway, elegant lounge, dining/sitting room, attractive fitted kitchen with a host of appliances, rear lobby and downstairs W.C.. At first floor are four bedrooms, one of which is perfect as a study. The bathroom features a shaped bath with rainhead shower over.", "https://media.rightmove.co.uk/dir/86k/85955/89791832/85955_10102732_IMG_20_0000_max_656x437.jpg"),
				new Property(FOR_SALE, 150000, DETACHED, "Hull", 4, "Luxury 4 bedroom detached home featuring contemporary kitchen / dining room with French doors leading to garden. Lounge with feature bay window, ground floor cloakroom with separate utility room. Master bedroom with en-suite shower room.", "https://premierpropertiesperth.co.uk/wp-content/uploads/2019/07/1-51.jpg"),
				new Property(FOR_SALE, 125000, SEMI_DETACHED, "Hull", 2, "One of the best presented properties seen for a long time, this wonderful two bedroom semi-detached home has been substantially extended in the past and now offers two reception rooms with incredible breakfast kitchen at ground floor, along with two double bedrooms and a family bathroom at first floor.", "https://www.ourproperty.co.uk/content/uploads/2007/05/semi-detatched-house-.jpg"),
				new Property(FOR_SALE, 100000, TERRACED, "Hull", 2, "With central heating and double glazing, the property briefly comprises entrance porch, hallway, lounge, kitchen, rear porch and to the first floor are two double bedrooms and a bathroom. Outside are gardens to the front, side and rear plus workshop and garage.", "https://media.rightmove.co.uk/dir/crop/10:9-16:9/40k/39234/58450948/39234_100275002495_IMG_01_0000_max_476x317.jpg"),
				new Property(FOR_SALE, 135000, SEMI_DETACHED, "Durham", 3, "The property has gas central heating (combi boiler), UPVC double glazing and offers spacious, well planned accommodation comprising, entrance porch, large L' shaped lounge/diner with feature fireplace, conservatory extension with patio doors to the rear garden and a modern refitted kitchen. There are 3 bedrooms to the first floor and a bathroom/wc with modern white suite. Driveway and gravelled garden to the front, pleasant enclosed 'south west' facing garden to the rear with patio area and small lawn. ", "https://s3.eu-west-2.amazonaws.com/standoutproperty/Media/3939cbab-fc70-4b14-bb7d-4105b919f3c9/8dbdb0de-504a-42bf-a639-a2c60dbf1ff8/brr-gj9105a2hz-17a9bce7d1accc659d6427ac9f7298eb.jpg"),
				new Property(FOR_SALE, 155000, DETACHED, "Durham", 4, "Much improved by the current owners the property offers spacious, well planned accommodation comprising, entrance porch, hallway, lounge with feature fireplace, fantastic open plan sitting/dining room with patio doors to the rear garden and archway to the kitchen with wall and base units. To the first floor are 4 bedrooms (3 doubles), family bathroom and a separate shower room both with white suites. Block paved driveway to the front providing ample parking. Lovely enclosed south facing rear garden mainly laid to lawn and overlooking countryside. EARLY VIEWING RECOMMENDED ", "https://media.rightmove.co.uk/dir/crop/10:9-16:9/72k/71919/92888069/71919_33dddce7-6991-4b1a-8fda-b689bea6c245-20_4_38_101368_IMG_01_0000_max_476x317.jpg"),
				new Property(FOR_SALE, 140000, FLAT, "Durham", 2, "Urban Base are pleased to offer this luxury two bedroom apartment within Freemans Quay. Combining luxury with accessibility, The accommodation briefly comprises of; entrance hall, living room combining an open plan kitchen with centre island breakfast bar, ground floor balcony, master bedroom, fully tiled stylish en-suite, main bathroom and second double bedroom. Viewing is highly recommended to fully appreciate this luxury city base. NB: No parking is included.", "https://odis.homeaway.com/odis/listing/cfc4ee9c-216d-4b16-ade4-8e74333e52d9.c10.jpg"),
				new Property(FOR_SALE, 165000, DETACHED, "Leeds", 4, "A modern, four bedroomed, detached property situated in a sought after development close to the heart of Crossgates which boasts a variety of shops, cafes and amenities. There is also access to good transport links which provide access into Leeds City Centre and surrounding areas. In brief, the accommodation comprises: entrance hall, lounge and kitchen to the ground floor. To the first floor, there are four bedrooms with the master having en-suite facilities and a house bathroom. Externally, the property features off street parking for up to two cars and a privately enclosed rear garden.", "https://media.onthemarket.com/properties/7507907/1290030266/composite.jpg"),
				new Property(FOR_SALE, 145000, SEMI_DETACHED, "Leeds", 3, "The accommodation briefly comprises; to the ground floor, entrance hall, guest w.c, lounge, large family dining kitchen with French doors leading on to the rear garden. White modern fitted kitchen with integrated appliances. To the first floor are three bedrooms (two with fitted wardrobes) and a large four piece family bathroom with separate walk-in shower enclosure. Externally there is parking for numerous cars and large detached garage with utility area.", "https://i.dailymail.co.uk/i/pix/scaled/2014/04/23/article-2611281-034567D2000005DC-344_636x382.jpg"),
				new Property(FOR_SALE, 185000, BUNGALOW, "Leeds", 1, "A skilfully extended, well presented one bedroom detached bungalow, set in sought after location of Alwoodley. Close to local amenities, outstanding schools and good transport links into Leeds and Harrogate. Don't miss out on this great opportunity and book your viewing today on .", "https://i.ytimg.com/vi/kgCzRUzu60E/maxresdefault.jpg"),
				new Property(FOR_SALE, 115000, FLAT, "Stoke", 1, "This property at the heart of the village of Blythe Bridge contains two self contained flats both offer well proportioned accommodation and features of each flat include a double bedroom, a generously proportioned lounge, a kitchen with dining area, UPVC double glazing and gas central heating.", "https://www.edinburghnews.scotsman.com/webimg/b25lY21zOjU3OWZhYzNiLWY4MmItNGEzZS05NDMzLTUwNWNlN2U2ODhhOTo4NGU3ODhhMi1jODM1LTRmZGEtODgyZi01ZGNlYjlmYmI4NDU=.jpg?width=640"),
				new Property(FOR_SALE, 130000, SEMI_DETACHED, "Stoke", 3, "A stunning Grade II listed home perfectly positioned in an extremely enviable location. With spacious accommodation on offer set over three floors, forming part of the historic Duke of Sutherland Trentham Estate. The ground floor is flooded with natural light and offers varied areas in which to relax . An open plan style layout leads to a vast kitchen/dining and family area which includes central island, fitted appliances, solid oak units and a utility and laundry room. French doors lead straight out from the dining space to the pretty and private raised decked area and there is also a private study/snug with feature window and a stylish guest WC. The first floor landing leads to a generous living room with feature windows and a contemporary fireplace. At the end of the hallway, the master bedroom suite, with its luxurious en-suite bathroom and fitted wardrobes is just as impressive as it sounds. The comfortable third bedroom has sole use of a shower room and at the top of the house there is a guest suite complete with en-suite shower room.", "https://media.istockphoto.com/photos/modern-home-picture-id181123941?k=6&m=181123941&s=612x612&w=0&h=_r393W2q_NV4iCxOPc0QmTTcUFKB08GTzn0jdvC1exM="),
				new Property(FOR_SALE, 140000, TERRACED, "Stoke", 3, "Location, Location, Location! Those three little words say it all. This stunning Grade ll listed home offers spacious accommodation laid out over three floors within the prestigious Trentham Park, just a few minutes walk from the renowned Trentham Gardens, the property offers a lovely low maintenance garden and has a garage and further off road parking. ", "https://www.thehouseshop.com/property-blog/wp-content/uploads/2018/10/What-is-a-terraced-house.jpg"),
				new Property(FOR_SALE, 175000, SEMI_DETACHED, "Newcastle", 3, "The Corbridge is an exceptional, light and spacious three bedroom home based over three floors with allocated parking. On the ground floor, you will find a modern kitchen/dining area, a W.C and a generously sized lounge with French doors for access to the rear garden. The first floor comprises of two ample sized bedrooms and a stylish family bathroom. The master bedroom is on the second floor and features two storage cupboards and an en-suite for added privacy.", "https://premierpropertiesperth.co.uk/wp-content/uploads/2019/08/1-23.jpg"),
				new Property(FOR_SALE, 150000, SEMI_DETACHED, "Newcastle", 4, "This fabulous 4 bedroomed stone built offers impressive accommodation over 4 levels. Occupying a coveted position within this highly sought after gated redevelopment of a former farm steading, and with gas heating and sealed unit double glazing, the Reception Hall, with storage cupboard and oak floor, has a Cloakroom/WC, with wc and wash basin with large mirror over. The focal point of the 20' Lounge is a gas fired stove within a rustic brick fireplace. French doors open to the garden. The 20' Breakfasting Kitchen is well fitted with a good range of units, with sink unit, granite work surfaces, Stoves dual fuel range style cooker with extractor over, microwave, integral dishwasher with matching door, American style fridge/freezer, central island, oak floor, picture window and French doors. The Utility Room is fitted with wall and base units, sink unit, solid wood work surfaces, plumbing for a washer and door to the side. The Guest/Bedroom 2 is to the Lower Level, with French doors opening to a private Courtyard, and an En Suite Bathroom/WC, with wc with concealed cistern, wall mounted wash basin with large mirror over and storage under and panelled bath with mains shower over and screen. The Upper Level Landing has a Velux roof light. Bedroom 1 has a range of fitted wardrobes, a vaulted ceiling and dramatic floor to ceiling window affording fabulous views. The En Suite Bathroom/WC has a wc, wash basin with mirror over, double ended bath and shower quadrant with mains shower. Bedroom 3 has a vaulted ceiling and En Suite Shower/WC with wc, wall mounted wash basin with storage under and mirror and light over and double shower enclosure with mains shower unit. Bedroom 4 has stairs up to a mezzanine level En Suite Shower/WC, with wc, wall mounted wash basin with mirror over and storage under and double shower enclosure with mains shower unit. Externally, this property enjoys generous gardens, ideal for family use and ample parking for a number of cars.", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQZL-FEWHAGy3Fz48x7lJiBXwgVPMVMLJIvszvOVdlfpd8zCLmo&usqp=CAU"),
				new Property(TO_LET, 650, DETACHED, "Hull", 3, "This detached home is located on Kingswood, close to well regarded schools and local amenities including a supermarket, a cinema and a range of retail outlets and restaurants. The property would be perfect for a family as it is ready to move into and offers ample living space. The property is available with no onward chain and benefits from front and rear gardens as well as a garage with off-street parking space and internally boasts a gorgeous living room, a stunning kitchen/diner with utility room off, a convenient downstairs WC, two double bedrooms with en-suite shower-room to master, a single third bedroom and a stylish family bathroom.", "https://media.rightmove.co.uk/dir/crop/10:9-16:9/150k/149891/90446150/149891_66cad1ff-17c7-4044-ad90-d4320d5e813a-283_4_37_101368_IMG_01_0000_max_476x317.jpg"),
				new Property(TO_LET, 500, SEMI_DETACHED, "Hull", 4, "This stunning bay fronted semi detached house stands in the highly desirable and leafy street scene of Elms Drive, ideally placed for local schools, shops and amenities. With its wealth of character and modern fittings this super family home also has the benefit of a good sized garden to enjoy. The accommodation has gas fired central heating, double glazing and comprises a spacious hallway, elegant lounge, dining/sitting room, attractive fitted kitchen with a host of appliances, rear lobby and downstairs W.C.. At first floor are four bedrooms, one of which is perfect as a study. The bathroom features a shaped bath with rainhead shower over.", "https://media.rightmove.co.uk/dir/86k/85955/89791832/85955_10102732_IMG_20_0000_max_656x437.jpg"),
				new Property(TO_LET, 550, DETACHED, "Hull", 4, "Luxury 4 bedroom detached home featuring contemporary kitchen / dining room with French doors leading to garden. Lounge with feature bay window, ground floor cloakroom with separate utility room. Master bedroom with en-suite shower room.", "https://premierpropertiesperth.co.uk/wp-content/uploads/2019/07/1-51.jpg"),
				new Property(TO_LET, 450, SEMI_DETACHED, "Hull", 2, "One of the best presented properties seen for a long time, this wonderful two bedroom semi-detached home has been substantially extended in the past and now offers two reception rooms with incredible breakfast kitchen at ground floor, along with two double bedrooms and a family bathroom at first floor.", "https://www.ourproperty.co.uk/content/uploads/2007/05/semi-detatched-house-.jpg"),
				new Property(TO_LET, 350, TERRACED, "Hull", 2, "With central heating and double glazing, the property briefly comprises entrance porch, hallway, lounge, kitchen, rear porch and to the first floor are two double bedrooms and a bathroom. Outside are gardens to the front, side and rear plus workshop and garage.", "https://media.rightmove.co.uk/dir/crop/10:9-16:9/40k/39234/58450948/39234_100275002495_IMG_01_0000_max_476x317.jpg"),
				new Property(TO_LET, 500, SEMI_DETACHED, "Durham", 3, "The property has gas central heating (combi boiler), UPVC double glazing and offers spacious, well planned accommodation comprising, entrance porch, large L' shaped lounge/diner with feature fireplace, conservatory extension with patio doors to the rear garden and a modern refitted kitchen. There are 3 bedrooms to the first floor and a bathroom/wc with modern white suite. Driveway and gravelled garden to the front, pleasant enclosed 'south west' facing garden to the rear with patio area and small lawn. ", "https://s3.eu-west-2.amazonaws.com/standoutproperty/Media/3939cbab-fc70-4b14-bb7d-4105b919f3c9/8dbdb0de-504a-42bf-a639-a2c60dbf1ff8/brr-gj9105a2hz-17a9bce7d1accc659d6427ac9f7298eb.jpg"),
				new Property(TO_LET, 550, DETACHED, "Durham", 4, "Much improved by the current owners the property offers spacious, well planned accommodation comprising, entrance porch, hallway, lounge with feature fireplace, fantastic open plan sitting/dining room with patio doors to the rear garden and archway to the kitchen with wall and base units. To the first floor are 4 bedrooms (3 doubles), family bathroom and a separate shower room both with white suites. Block paved driveway to the front providing ample parking. Lovely enclosed south facing rear garden mainly laid to lawn and overlooking countryside. EARLY VIEWING RECOMMENDED ", "https://media.rightmove.co.uk/dir/crop/10:9-16:9/72k/71919/92888069/71919_33dddce7-6991-4b1a-8fda-b689bea6c245-20_4_38_101368_IMG_01_0000_max_476x317.jpg"),
				new Property(TO_LET, 500, FLAT, "Durham", 2, "Urban Base are pleased to offer this luxury two bedroom apartment within Freemans Quay. Combining luxury with accessibility, The accommodation briefly comprises of; entrance hall, living room combining an open plan kitchen with centre island breakfast bar, ground floor balcony, master bedroom, fully tiled stylish en-suite, main bathroom and second double bedroom. Viewing is highly recommended to fully appreciate this luxury city base. NB: No parking is included.", "https://odis.homeaway.com/odis/listing/cfc4ee9c-216d-4b16-ade4-8e74333e52d9.c10.jpg"),
				new Property(TO_LET, 700, DETACHED, "Leeds", 4, "A modern, four bedroomed, detached property situated in a sought after development close to the heart of Crossgates which boasts a variety of shops, cafes and amenities. There is also access to good transport links which provide access into Leeds City Centre and surrounding areas. In brief, the accommodation comprises: entrance hall, lounge and kitchen to the ground floor. To the first floor, there are four bedrooms with the master having en-suite facilities and a house bathroom. Externally, the property features off street parking for up to two cars and a privately enclosed rear garden.", "https://media.onthemarket.com/properties/7507907/1290030266/composite.jpg"),
				new Property(TO_LET, 600, SEMI_DETACHED, "Leeds", 3, "The accommodation briefly comprises; to the ground floor, entrance hall, guest w.c, lounge, large family dining kitchen with French doors leading on to the rear garden. White modern fitted kitchen with integrated appliances. To the first floor are three bedrooms (two with fitted wardrobes) and a large four piece family bathroom with separate walk-in shower enclosure. Externally there is parking for numerous cars and large detached garage with utility area.", "https://i.dailymail.co.uk/i/pix/scaled/2014/04/23/article-2611281-034567D2000005DC-344_636x382.jpg"),
				new Property(TO_LET, 750, BUNGALOW, "Leeds", 1, "A skilfully extended, well presented one bedroom detached bungalow, set in sought after location of Alwoodley. Close to local amenities, outstanding schools and good transport links into Leeds and Harrogate. Don't miss out on this great opportunity and book your viewing today on .", "https://i.ytimg.com/vi/kgCzRUzu60E/maxresdefault.jpg"),
				new Property(TO_LET, 450, FLAT, "Stoke", 1, "This property at the heart of the village of Blythe Bridge contains two self contained flats both offer well proportioned accommodation and features of each flat include a double bedroom, a generously proportioned lounge, a kitchen with dining area, UPVC double glazing and gas central heating.", "https://www.edinburghnews.scotsman.com/webimg/b25lY21zOjU3OWZhYzNiLWY4MmItNGEzZS05NDMzLTUwNWNlN2U2ODhhOTo4NGU3ODhhMi1jODM1LTRmZGEtODgyZi01ZGNlYjlmYmI4NDU=.jpg?width=640"),
				new Property(TO_LET, 500, SEMI_DETACHED, "Stoke", 3, "A stunning Grade II listed home perfectly positioned in an extremely enviable location. With spacious accommodation on offer set over three floors, forming part of the historic Duke of Sutherland Trentham Estate. The ground floor is flooded with natural light and offers varied areas in which to relax . An open plan style layout leads to a vast kitchen/dining and family area which includes central island, fitted appliances, solid oak units and a utility and laundry room. French doors lead straight out from the dining space to the pretty and private raised decked area and there is also a private study/snug with feature window and a stylish guest WC. The first floor landing leads to a generous living room with feature windows and a contemporary fireplace. At the end of the hallway, the master bedroom suite, with its luxurious en-suite bathroom and fitted wardrobes is just as impressive as it sounds. The comfortable third bedroom has sole use of a shower room and at the top of the house there is a guest suite complete with en-suite shower room.", "https://media.istockphoto.com/photos/modern-home-picture-id181123941?k=6&m=181123941&s=612x612&w=0&h=_r393W2q_NV4iCxOPc0QmTTcUFKB08GTzn0jdvC1exM="),
				new Property(TO_LET, 450, TERRACED, "Stoke", 3, "Location, Location, Location! Those three little words say it all. This stunning Grade ll listed home offers spacious accommodation laid out over three floors within the prestigious Trentham Park, just a few minutes walk from the renowned Trentham Gardens, the property offers a lovely low maintenance garden and has a garage and further off road parking. ", "https://www.thehouseshop.com/property-blog/wp-content/uploads/2018/10/What-is-a-terraced-house.jpg"),
				new Property(TO_LET, 850, SEMI_DETACHED, "Newcastle", 3, "The Corbridge is an exceptional, light and spacious three bedroom home based over three floors with allocated parking. On the ground floor, you will find a modern kitchen/dining area, a W.C and a generously sized lounge with French doors for access to the rear garden. The first floor comprises of two ample sized bedrooms and a stylish family bathroom. The master bedroom is on the second floor and features two storage cupboards and an en-suite for added privacy.", "https://premierpropertiesperth.co.uk/wp-content/uploads/2019/08/1-23.jpg"),
				new Property(TO_LET, 500, SEMI_DETACHED, "Newcastle", 4, "This fabulous 4 bedroomed stone built offers impressive accommodation over 4 levels. Occupying a coveted position within this highly sought after gated redevelopment of a former farm steading, and with gas heating and sealed unit double glazing, the Reception Hall, with storage cupboard and oak floor, has a Cloakroom/WC, with wc and wash basin with large mirror over. The focal point of the 20' Lounge is a gas fired stove within a rustic brick fireplace. French doors open to the garden. The 20' Breakfasting Kitchen is well fitted with a good range of units, with sink unit, granite work surfaces, Stoves dual fuel range style cooker with extractor over, microwave, integral dishwasher with matching door, American style fridge/freezer, central island, oak floor, picture window and French doors. The Utility Room is fitted with wall and base units, sink unit, solid wood work surfaces, plumbing for a washer and door to the side. The Guest/Bedroom 2 is to the Lower Level, with French doors opening to a private Courtyard, and an En Suite Bathroom/WC, with wc with concealed cistern, wall mounted wash basin with large mirror over and storage under and panelled bath with mains shower over and screen. The Upper Level Landing has a Velux roof light. Bedroom 1 has a range of fitted wardrobes, a vaulted ceiling and dramatic floor to ceiling window affording fabulous views. The En Suite Bathroom/WC has a wc, wash basin with mirror over, double ended bath and shower quadrant with mains shower. Bedroom 3 has a vaulted ceiling and En Suite Shower/WC with wc, wall mounted wash basin with storage under and mirror and light over and double shower enclosure with mains shower unit. Bedroom 4 has stairs up to a mezzanine level En Suite Shower/WC, with wc, wall mounted wash basin with mirror over and storage under and double shower enclosure with mains shower unit. Externally, this property enjoys generous gardens, ideal for family use and ample parking for a number of cars.", "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQZL-FEWHAGy3Fz48x7lJiBXwgVPMVMLJIvszvOVdlfpd8zCLmo&usqp=CAU")));
		}
	}

}
